from groq import Groq
import smtplib
import schedule
import time
import requests
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# ============================================
#         🔑 YOUR CONFIGURATION
# ============================================
from dotenv import load_dotenv
import os

load_dotenv()

GROQ_API_KEY   = os.getenv("GROQ_API_KEY")
EMAIL_ADDRESS  = os.getenv("EMAIL_ADDRESS")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD")
CITY           = "Lahore"
# ============================================

MY_TASKS = [
    "Reply to important emails",
    "Work on AI automation project",
    "Exercise for 30 minutes",
    "Read for 20 minutes"
]


def get_live_weather(city):
    try:
        url = f"https://wttr.in/{city}?format=3"
        response = requests.get(url, timeout=5)
        return response.text.strip()
    except:
        return f"Sunny, 33C in {city}"


def get_news():
    try:
        url = "https://gnews.io/api/v4/top-headlines?lang=en&max=5&apikey=demo"
        response = requests.get(url, timeout=5)
        data = response.json()
        articles = data.get("articles", [])
        if articles:
            news_list = []
            for i, article in enumerate(articles[:5], 1):
                news_list.append(f"{i}. {article['title']}")
            return "\n".join(news_list)
        else:
            return "No news fetched today."
    except:
        return "Could not fetch news today."


def get_tasks_from_file():
    try:
        with open("tasks.txt", "r") as f:
            tasks = [line.strip() for line in f.readlines() if line.strip()]
        return tasks
    except:
        return MY_TASKS


def generate_ai_plan(tasks, weather, news):
    client = Groq(api_key=GROQ_API_KEY)
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{
            "role": "user",
            "content": f"""
            My tasks for today: {tasks}
            Today's weather: {weather}
            Today's top news: {news}

            Please give me:
            1. A short energetic morning message (2 lines)
            2. Best order to complete my tasks with reasons
            3. 2-3 productivity tips based on the weather
            4. One interesting thing from today's news worth knowing

            Keep it friendly, motivating and concise!
            """
        }]
    )
    return response.choices[0].message.content


def send_email(plan, weather, news):
    msg = MIMEMultipart('alternative')
    msg['Subject'] = f'Your AI Daily Briefing - {time.strftime("%B %d, %Y")}'
    msg['From']    = EMAIL_ADDRESS
    msg['To']      = EMAIL_ADDRESS

    html = f"""
    <html>
    <body style="margin:0; padding:0; background:#f0f4f8; font-family: Arial, sans-serif;">
      <div style="max-width:600px; margin:30px auto; background:white; border-radius:16px; overflow:hidden; box-shadow:0 4px 20px rgba(0,0,0,0.1);">

        <div style="background:#534AB7; padding:40px; text-align:center;">
          <h1 style="color:white; margin:0; font-size:28px;">Good Morning, Ali!</h1>
          <p style="color:rgba(255,255,255,0.85); margin:8px 0 0;">{time.strftime("%A, %B %d, %Y")}</p>
        </div>

        <div style="background:#FAEEDA; padding:20px 30px; border-left:5px solid #BA7517;">
          <h2 style="margin:0 0 8px; color:#854F0B;">Live Weather</h2>
          <p style="margin:0; font-size:16px; color:#633806;">{weather}</p>
        </div>

        <div style="padding:25px 30px; background:#f9f9f9;">
          <h2 style="color:#2c3e50; margin:0 0 12px;">Top News</h2>
          <p style="margin:0; font-size:15px; color:#555; line-height:1.8;">{news.replace(chr(10), '<br>')}</p>
        </div>

        <div style="padding:25px 30px;">
          <h2 style="color:#2c3e50; margin:0 0 12px;">Your AI Daily Plan</h2>
          <div style="background:#f0f4ff; border-radius:10px; padding:20px; font-size:15px; color:#333; line-height:1.8;">
            {plan.replace(chr(10), '<br>')}
          </div>
        </div>

        <div style="background:#2c3e50; padding:20px; text-align:center;">
          <p style="color:rgba(255,255,255,0.7); margin:0; font-size:13px;">
            Generated by your AI Daily Briefing Bot<br>
            Have an amazing and productive day!
          </p>
        </div>

      </div>
    </body>
    </html>
    """

    msg.attach(MIMEText(html, 'html'))

    try:
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
            server.login(EMAIL_ADDRESS, EMAIL_PASSWORD)
            server.send_message(msg)
        print(" email sent successfully!")
    except Exception as e:
        print(f"❌ Email error: {e}")


def run_briefing():
    print("🤖 Generating your Super Daily Briefing...")

    print("🌤️ Fetching live weather...")
    weather = get_live_weather(CITY)
    print(f"   {weather}")

    print("📰 Fetching today's news...")
    news = get_news()

    print("📋 Reading your tasks...")
    tasks = get_tasks_from_file()

    print("🧠 Asking AI to create your plan...")
    plan = generate_ai_plan(tasks, weather, news)

    print("\n--- AI PLAN ---")
    print(plan)
    print("---------------\n")

    send_email(plan, weather, news)


schedule.every().day.at("07:00").do(run_briefing)

print("🚀 Super Daily Briefing Bot is running...")
print("⏰ Scheduled for 7:00 AM every day")
print("💡 Press Ctrl+C to stop\n")

run_briefing()

while True:
    schedule.run_pending()
    time.sleep(60)